version: '3.8'

services:
  db_bigbox:
    image: "postgres:11"
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/bigbox/data/
    ports: 
      - 5430:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
        - 8880:8000
    volumes:
        - .:/app
    depends_on: 
      - db_bigbox

volumes:
  database:
