# Generated by Django 2.2 on 2021-08-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbox', '0002_auto_20210808_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='slug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
